server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Deshabilitar caché para index.html (opcional, pero ayuda durante el desarrollo)
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Configuración de caché para archivos estáticos (mejor rendimiento)
    location ~* \.(css|js|gif|jpe?g|png|ico|svg|eot|ttf|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/plain application/xml application/json application/javascript text/css;
}